Create roadmap.md
Comcast/xGitGuard pull request #33
Opened 2024-06-25 06:52 UTC by radhi1991

Adding Roadmap file

2024-07-08 09:19 UTC, dinpraka commented on roadmap.md
> +| Custom keyword search     | Search for specific keywords within repositories       | ✅ Done | [preethid03](https://github.com/preethid03) |
1. This was not completed

2024-07-08 11:50 UTC, radhi1991 commented
@dinpraka  - Made the requested changes

2024-07-08 12:45 UTC, dinpraka commented on roadmap.md
> +| Feature                   | Description                                             | Status | Developer (GitHub ID) |
This should come under separate feature
Filescanner scope is different. Please fix this

2024-07-08 12:46 UTC, dinpraka requested changes
1. Roadmap for filescanner is not right. Custom keyword search would be separate feature
2. Add line number feature to roadmap

2024-07-08 17:42 UTC, radhi1991 commented on roadmap.md
> +| Multi-language package manager | Manage code checks and linters before commits       |  🚧 To Do | [](https://github.com/preethid030) |
Done

2024-07-09 10:58 UTC, dinpraka approved these changes

2024-07-09 10:59 UTC, merged