Fixline numberissue
Comcast/xGitGuard pull request #38
Opened 2024-09-05 03:00 UTC by Dhanushkarthik29

2024-11-12 04:16 UTC, sai100 commented on xgitguard/github-enterprise/enterprise_cred_detections.py
> +                linenumber=findLineNumber(code_content.split("\n"),code_line)
let's rename variable since it is is not the line number, rather a list of code lines, Also we can move this line to the utility function.

2024-11-12 04:24 UTC, sai100 requested changes
We are appending the result of findLineNumber function, but we have no respective column in xgg_configs.yaml file for the secrets data columns.

Also please format the code using black formatter.

2025-02-25 18:39 UTC, radhi1991 commented
@nishabalamurugan

2025-05-12 11:51 UTC, jansiraj requested changes

2025-05-12 11:51 UTC, jansiraj commented on xgitguard/utilities/file_utilities.py
> +def findLineNumber(code_content,code_line):
Change the function name as per pep8 standards

2026-04-14 06:46 UTC, closed without merging

2026-04-14 06:46 UTC, jansiraj commented
closing this as already different pr raised for this change and code got merged